---
# htpasswd -nbm admin admin@123
# admin:$apr1$rQx7Vxpj$VqleutQGatsBWuuwkupU.0
alertmanager:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      certmanager.k8s.io/acme-http01-edit-in-place: "false"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      nginx.ingress.kubernetes.io/auth-secret: alertmanager-auth
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/affinity: cookie
    hosts:
      - alertmanager.kube.alifakoor.ir        # AlertManager Url
    ingressClassName: nginx
    tls:
      - secretName: alertmanager-general-tls
        hosts:
          - alertmanager.kube.alifakoor.ir    # AlertManager Url for certificate

  alertmanagerSpec:                       # AlertManager PVC
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: remote-disk
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

  extraSecret:
    name: "alertmanager-auth"
    data:
      auth: |
        admin:$apr1$rQx7Vxpj$VqleutQGatsBWuuwkupU.0

grafana:
  defaultDashboardsTimezone: Asia/Tehran
  adminPassword: Grafana_Admin_Password_sdfsfewkmrkjnrsjfnwek       # Grafana admin user Password
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      certmanager.k8s.io/acme-http01-edit-in-place: "false"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana.kube.alifakoor.ir                 # Grafana Url
    ingressClassName: nginx
    tls:
      - secretName: grafana-general-tls
        hosts:
          - grafana.kube.alifakoor.ir             # Grafana Url for Certificate
  persistence:                                # Grafana PVC
    # type: pvc
    # enabled: true
    # storageClassName: remote-disk
    # accessModes:
    #   - ReadWriteOnce
    # size: 10Gi
    # finalizers:
    #   - kubernetes.io/pvc-protection
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: remote-disk
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

kubeControllerManager:
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true

kubeEtcd:
  enabled: false
  serviceMonitor:
    enabled: true
    scheme: http
    insecureSkipVerify: false
    serverName: localhost
    caFile: /etc/prometheus/secrets/etcd-client-cert/etcd-ca
    certFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client
    keyFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client-key
  service:
    enabled: true
    port: 2381
    targetPort: 2381

kubeScheduler:
  service:
    port: 10259
    targetPort: 10259
  serviceMonitor:
    https: true
    insecureSkipVerify: true

kubeProxy:
  service:
    port: 10249
    targetPort: 10249

kubelet:
  enabled: true
  namespace: kube-system

prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      certmanager.k8s.io/acme-http01-edit-in-place: "false"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      nginx.ingress.kubernetes.io/auth-secret: prometheus-auth
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/affinity: cookie
    hosts:
      - prometheus.kube.alifakoor.ir                # Prometheus Url
    ingressClassName: nginx
    tls:
      - secretName: prometheus-general-tls
        hosts:
          - prometheus.kube.alifakoor.ir             # Prometheus Url for certificate

  prometheusSpec:                                # Prometheus PVC
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: remote-disk
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1.5Gi

  extraSecret:
    name: "prometheus-auth"
    data:
      auth: |
        admin:$apr1$rQx7Vxpj$VqleutQGatsBWuuwkupU.0
