apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup-cronjob
  namespace: kube-system
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          # Tolerate master taint
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          hostNetwork: true
          containers:
          - name: etcd-backup
            image: h0x3ein/etcd-mc:latest
            args:
            - https://127.0.0.1:2379
            volumeMounts:
            - mountPath: /var/lib/etcd
              name: etcd-datadir
            - mountPath: /certs
              name: etcd-certs
            env:
              - name: MINIO_ALIAS_NAME
                value: taav
              - name: MINIO_SERVER
                value: http://object.devops.local
              - name: MINIO_BUCKET
                value: etcd-backup
              - name: MINIO_API_VERSION
                value: S3v4
              - name: MINIO_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: etcd-backup-secret
                    key: MINIO_ACCESS_KEY
              - name: MINIO_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: etcd-backup-secret
                    key: MINIO_SECRET_KEY
          volumes:
          - name: etcd-datadir
            hostPath:
              path: /var/lib/etcd
          - name: etcd-certs
            hostPath:
              path: /etc/kubernetes/pki/etcd/
          restartPolicy: Never

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup-secret
  namespace: kube-system
type: Opaque
data:
  MINIO_ACCESS_KEY: "YWRtaW5hc2Rhc2Rhc2Q="  # base64-encoded "adminasdasdasd"
  MINIO_SECRET_KEY: "YWRtaWFzZGFzZGFzZG4="  # base64-encoded "admiasdasdasdn