mode: standalone

image:
  repository: quay.io/minio/minio
  #tag: RELEASE.2025-01-20T14-49-07Z
  tag: RELEASE.2024-12-18T13-15-44Z
  pullPolicy: IfNotPresent

rootUser: "adminasdasdasd"
rootPassword: "admiasdasdasdn"
mountPath: "/data"


resources:
  requests:
    memory: 1G
    cpu: 500m
  limit:
    memory: 5G
    cpu: 1000m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi

service:
  name: minio
  type: ClusterIP
  port: 9000

consoleService:
  name: minio-console
  type: ClusterIP
  port: 9001

#extraArgs:
#  - --console-address :9001

#environment:
#  MINIO_SERVER_URL: http://object.kube.mecan.ir
#  MINIO_BROWSER_REDIRECT_URL: http://minio.kube.mecan.ir

consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /
  hosts:
    - minio.devops.local
  tls: []

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /
  hosts:
    - object.devops.local
  tls: [] 